export interface IEmployee{
      emailId: string,
      city: string,
      twitter_handle: string,
      keywordSupport: string,
      country: string,
      imageURL: string,
      venue: string,
      searchTerms: string,
      confName: string,
      state: string,
      long: number,
      confEndDate: string,
      conference_id: number,
      lat: number,
      user_id:  number,
      confUrl: string,
      confStartDate: string,
      entryType: string,
      confRegUrl: string,
}